//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseFirstDbEntities2 : DbContext
    {
        public DatabaseFirstDbEntities2()
            : base("name=DatabaseFirstDbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MService> MServices { get; set; }
        public virtual DbSet<Registeration> Registerations { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<BookingTbl> BookingTbls { get; set; }
        public virtual DbSet<Timeslot> Timeslots { get; set; }
    }
}
